version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=cmk_pass
      - POSTGRES_USER=cmk
      - POSTGRES_DB=cmk_dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
