import { db, Product } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(Product).values([
    {
      id: 1,
      name: 'Mouse',
      price: 100,
      image: 'mouse',
      description: 'A high-quality mouse',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 2,
      name: 'Keyboard',
      price: 50,
      image: 'keyboard',
      description: 'A high-quality keyboard',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 3,
      name: 'Headset',
      price: 300,
      image: 'headset',
      description: 'A high-quality headset',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 4,
      name: 'Mouse',
      price: 100,
      image: 'mouse',
      description: 'A high-quality mouse',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 5,
      name: 'Keyboard',
      price: 50,
      image: 'keyboard',
      description: 'A high-quality keyboard',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 6,
      name: 'Headset',
      price: 300,
      image: 'headset',
      description: 'A high-quality headset',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 7,
      name: 'Mouse',
      price: 100,
      image: 'mouse',
      description: 'A high-quality mouse',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 8,
      name: 'Keyboard',
      price: 50,
      image: 'keyboard',
      description: 'A high-quality keyboard',
      rating: 4.5,
      reviews: 150,
    },
    {
      id: 9,
      name: 'Headset',
      price: 300,
      image: 'headset',
      description: 'A high-quality headset',
      rating: 4.5,
      reviews: 150,
    },
  ]);
}
